#!/bin/bash

# generate random IP address(es). number of IPs is specified as an argument

a=$RANDOM; b=$RANDOM; c=$RANDOM; d=$RANDOM
let "a %= 255"; let "b %= 255 "; let "c %= 255 "; let "d %= 255"


if [[ $# -ne 1  ]]
then
	echo "usage: $0 <number>"
	exit 1	
fi

for((i=0;i<$1;++i))
do
	a=$RANDOM; b=$RANDOM; c=$RANDOM; d=$RANDOM
	let "a %= 255"; let "b %= 255 "; let "c %= 255 "; let "d %= 255"

	echo $a.$b.$c.$d
done
