#!/bin/bash
wget -r -nd -nv --delete-after -U 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.8.1.3) Gecko/20070309 Firefox/2.0.0.3' $@ 2>&1 | grep -E '^[0-9]{2}:[0-9]{2}:[0-9]{2} URL:' | cut -d':' -f4- | cut -d'[' -f1 2> /dev/null
